require "rails/railtie"
require "rails/engine"
require "action_view"
require "rouge"

require "rouge/rails/version"
require "rouge/rails/template_handler"
require "rouge/rails/railtie"
require "rouge/rails/configuration"
require "rouge/rails/engine"
